#!/bin/bash

# ROCM-AI-Installer
# Copyright © 2023-2025 Mateusz Dera

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

set -e

# Version
VERSION="10.0"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/.env"

# Default values
DEFAULT_HSA_VERSION="11.0.0"
DEFAULT_GFX="gfx1100"
DEFAULT_AI_DIR="${HOME}/AI"

# Colors
export NEWT_COLORS='
root=,black
textbox=white,black
border=blue,black
window=white,black
title=yellow,black
button=black,yellow
compactbutton=yellow,black
listbox=white,black
actlistbox=black,white
actsellistbox=black,yellow
checkbox=white,black
actcheckbox=yellow,black
'

# Files
source $SCRIPT_DIR/interfaces.sh
source $SCRIPT_DIR/backup.sh

# Load existing configuration if available
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
        HSA_VERSION="${HSA_OVERRIDE_GFX_VERSION:-$DEFAULT_HSA_VERSION}"
        GFX_VERSION="${TARGET_GFX:-$DEFAULT_GFX}"
        AI_DIR="${AI_HOST_DIR:-$DEFAULT_AI_DIR}"
    else
        HSA_VERSION="$DEFAULT_HSA_VERSION"
        GFX_VERSION="$DEFAULT_GFX"
        AI_DIR="$DEFAULT_AI_DIR"
    fi
}

# Save configuration
save_config() {
    cat > "$CONFIG_FILE" << EOF
# ROCm Container Configuration
# Generated by install.sh on $(date)

# HSA Override GFX Version (for GPU compatibility)
HSA_OVERRIDE_GFX_VERSION=${HSA_VERSION}

# Target GFX Architecture
TARGET_GFX=${GFX_VERSION}

# AI Workspace Directory (host path)
AI_HOST_DIR=${AI_DIR}
EOF
    echo "Configuration saved to: $CONFIG_FILE"
}

# Check if whiptail is available
check_whiptail() {
    if ! command -v whiptail &> /dev/null; then
        echo "Error: whiptail is not installed. Please install it first:"
        echo "  sudo apt install whiptail"
        exit 1
    fi
}

# Configure GFX
configure_gfx() {
    local new_gfx
    new_gfx=$(whiptail --title "Target GFX Architecture" \
        --inputbox "Enter Target GFX Architecture:\n\nFor AMD Radeon RX 7900 XTX use: gfx1100\nFor other GPUs, run 'rocminfo' to find your GPU architecture.\n\nCurrent value: ${GFX_VERSION}" \
        14 70 "$GFX_VERSION" 2>&1 > /dev/tty)

    if [ $? -eq 0 ] && [ -n "$new_gfx" ]; then
        GFX_VERSION="$new_gfx"
        save_config
        whiptail --title "Success" --msgbox "GFX Architecture set to: ${GFX_VERSION}" 8 50 2>&1 > /dev/tty
    fi
}

# Configure HSA Override
configure_hsa() {
    local new_hsa
    new_hsa=$(whiptail --title "HSA Override GFX Version" \
        --inputbox "Enter HSA_OVERRIDE_GFX_VERSION:\n\nFor AMD Radeon RX 7900 XTX use: 11.0.0\nFor other GPUs, check AMD documentation.\n\nCurrent value: ${HSA_VERSION}" \
        14 70 "$HSA_VERSION" 2>&1 > /dev/tty)

    if [ $? -eq 0 ] && [ -n "$new_hsa" ]; then
        HSA_VERSION="$new_hsa"
        save_config
        whiptail --title "Success" --msgbox "HSA Override set to: ${HSA_VERSION}" 8 50 2>&1 > /dev/tty
    fi
}

# Configure Path
configure_path() {
    local new_path
    new_path=$(whiptail --title "AI Workspace Directory" \
        --inputbox "Enter the host directory to mount as container workspace:\n\nThis directory will be created if it doesn't exist.\n\nCurrent value: ${AI_DIR}" \
        14 70 "$AI_DIR" 2>&1 > /dev/tty)

    if [ $? -eq 0 ] && [ -n "$new_path" ]; then
        # Expand tilde to full path
        new_path="${new_path/#\~/$HOME}"
        AI_DIR="$new_path"

        # Create directory if it doesn't exist
        # Note: Ownership will be managed by Podman's :U option during container runtime
        if [ ! -d "$AI_DIR" ]; then
            if whiptail --title "Create Directory" --yesno "Directory '$AI_DIR' does not exist.\n\nDo you want to create it?" 10 60 2>&1 > /dev/tty; then
                if ! mkdir -p "$AI_DIR"; then
                    whiptail --title "Error" --msgbox "Failed to create directory: ${AI_DIR}\n\nPlease check permissions." 10 60 2>&1 > /dev/tty
                    return 1
                fi

                # Set proper permissions (ownership handled by Podman :U)
                chmod 775 "$AI_DIR" 2>/dev/null || true

                save_config
                whiptail --title "Success" --msgbox "Directory created: ${AI_DIR}\nPermissions: 775\n\nNote: Ownership will be managed by Podman when container starts." 12 70 2>&1 > /dev/tty
            else
                return 0
            fi
        else
            # Ensure existing directory has proper permissions
            chmod 775 "$AI_DIR" 2>/dev/null || true

            save_config
            whiptail --title "Success" --msgbox "Path set to: ${AI_DIR}\n\nNote: Ownership will be managed by Podman when container starts." 10 70 2>&1 > /dev/tty
        fi
    fi
}

# Create Container
create_container() {
    if ! command -v podman-compose &> /dev/null; then
        whiptail --title "Error" --msgbox "podman-compose is not installed!\n\nPlease install Podman first from the Basic Install menu." 10 60 2>&1 > /dev/tty
        return
    fi

    if whiptail --title "Create Container" --yesno "This will:\n1. Stop existing container (podman-compose down)\n2. Build new container (podman-compose build)\n3. Start container (podman-compose up -d)\n\nContinue?" 14 60 2>&1 > /dev/tty; then
        # Ensure AI_DIR exists
        if [ -n "$AI_DIR" ]; then
            if [ ! -d "$AI_DIR" ]; then
                echo "Creating directory $AI_DIR..."
                if ! mkdir -p "$AI_DIR"; then
                    whiptail --title "Error" --msgbox "Failed to create directory: ${AI_DIR}\n\nCannot proceed with container creation." 10 60 2>&1 > /dev/tty
                    return 1
                fi
            fi

            echo "Setting permissions on $AI_DIR..."
            # Set permissions (ownership will be handled by Podman :U option)
            if ! chmod -R 775 "$AI_DIR" 2>/dev/null; then
                echo "Warning: Could not set permissions on $AI_DIR, but continuing..."
            fi

            echo "Directory $AI_DIR ready for container mount"
        fi

        echo "Stopping existing containers..."
        podman-compose down

        echo "Building container..."
        podman-compose build

        echo "Starting container..."
        podman-compose up -d

        whiptail --title "Success" --msgbox "Container created and started successfully!\n\nTo enter the container, run:\npodman exec -it rocm /bin/bash" 12 60 2>&1 > /dev/tty
    fi
}

# Text generation web UI
text_generation_web_ui() {
    second=true
    while $second; do
        
        choice=$(whiptail --title "Text generation" --menu "Choose an option:" 15 100 4 --cancel-button "Back" \
            1 "Backup" \
            2 "Install" \
            3 "Restore" \
            2>&1 > /dev/tty)
        

        if [ $status -ne 0 ]; then
            return 0
        fi

        case "$choice" in
            "1")
                text_generation_web_ui_backup
                ;;
            "2")
                install_text_generation_web_ui
                ;;
            "3")
                text_generation_web_ui_restore
                ;;
            "")
                echo "Previous menu..."
                second=false
                ;;
            *)
                echo "Invalid selection."
                second=false
                ;;
        esac
    done
}

text_generation_web_ui_backup() {
    CHOICES=$(whiptail --checklist "Backup:" 14 50 4 --cancel-button "Back" \
        1 "Backup models" ON \
        2 "Backup characters" ON \
        3 "Backup presets" ON \
        4 "Backup instruction-templates" ON 3>&1 1>&2 2>&3)

    status=$?
    
    if [ $status -ne 0 ]; then
        return 0
    fi

    perform_textgen_backup "$CHOICES"
}

text_generation_web_ui_restore() {
    CHOICES=$(whiptail --checklist "Restore:" 14 50 4 --cancel-button "Back" \
        1 "Restore models" ON \
        2 "Restore characters" ON \
        3 "Restore presets" ON \
        4 "Restore instruction-templates" ON 3>&1 1>&2 2>&3)

    status=$?
    
    if [ $status -ne 0 ]; then
        return 0
    fi

    perform_textgen_restore "$CHOICES"
}

# SillyTavern
sillytavern() {
    second=true
    while $second; do
        
        choice=$(whiptail --title "SillyTavern" --menu "Choose an option:" 15 100 4 --cancel-button "Back" \
            1 "Backup" \
            2 "Install" \
            3 "Install WhisperSpeech web UI extension" \
            4 "Restore" \
            2>&1 > /dev/tty)
        status=$?
        

        if [ $status -ne 0 ]; then
            return 0
        fi
        
        case "$choice" in
            "1")
                sillytavern_backup
                ;;
            "2")
                install_sillytavern
                ;;
            "3")
                install_sillytavern_whisperspeech_web_ui
                ;;
            "4")
                sillytavern_restore
                ;;
            "")
                echo "Previous menu..."
                second=true
                ;;
            *)
                echo "Invalid selection."
                second=true
                ;;
        esac
    done
}

# Backup SillyTavern
sillytavern_backup() {
    CHOICES=$(whiptail --checklist "Backup:" 21 50 14 --cancel-button "Back" \
        1 "Backup config.yaml" ON \
        2 "Backup settings.json" ON \
        3 "Backup characters" ON \
        4 "Backup groups" ON \
        5 "Backup worlds" ON \
        6 "Backup chats" ON \
        7 "Backup group chats" ON \
        8 "Backup user avatars images" ON \
        9 "Backup backgrounds images" ON \
        10 "Backup themes" ON \
        11 "Backup presets" ON \
        12 "Backup context" ON \
        13 "Backup instruct" ON \
        14 "Backup sysprompt" ON 3>&1 1>&2 2>&3)

    status=$?
    
    if [ $status -ne 0 ]; then
        return 0
    fi

    perform_sillytavern_backup "$CHOICES"
}

# Restore SillyTavern
sillytavern_restore() {
    CHOICES=$(whiptail --checklist "Restore:" 21 50 14 --cancel-button "Back" \
        1 "Restore config.yaml" ON \
        2 "Restore settings.json" ON \
        3 "Restore characters" ON \
        4 "Restore groups" ON \
        5 "Restore worlds" ON \
        6 "Restore chats" ON \
        7 "Restore group chats" ON \
        8 "Restore user avatars images" ON \
        9 "Restore backgrounds images" ON \
        10 "Restore themes" ON \
        11 "Restore presets" ON \
        12 "Restore context" ON \
        13 "Restore instruct" ON \
        14 "Restore sysprompt" ON 3>&1 1>&2 2>&3)

    status=$?
    
    if [ $status -ne 0 ]; then
        return 0
    fi

    perform_sillytavern_restore "$CHOICES"
}

# Text generation
text_generation() {
    second=true
    while $second; do
        
        choice=$(whiptail --title "Text generation" --menu "Choose an option:" 15 100 4 --cancel-button "Back" \
            1 "Install KoboldCPP" \
            2 "Text generation web UI" \
            3 "SillyTavern" \
            4 "Install llama.cpp" \
            2>&1 > /dev/tty)
        status=$?
        

        if [ $status -ne 0 ]; then
            return 0
        fi

        case "$choice" in
            "1")
                install_koboldcpp
                ;;
            "2")
                text_generation_web_ui
                ;;
            "3")
                sillytavern
                ;;
            "4")
                install_llama_cpp
                ;;
            "")
                echo "Previous menu..."
                second=false
                ;;
            *)
                echo "Invalid selection."
                second=false
                ;;
        esac
    done
}

# Image & Video generation
image_generation() {
    second=true
    while $second; do
        
        choice=$(whiptail --title "Image generation" --menu "Choose an option:" 15 100 2 --cancel-button "Back" \
            1 "ComfyUI" \
            2>&1 > /dev/tty)
        status=$?
        
        if [ $status -ne 0 ]; then
            return 0
        fi

        case "$choice" in
            "1")
                comfyui_addons
                ;;
            "")
                echo "Previous menu..."
                second=false
                ;;
            *)
                echo "Invalid selection."
                second=false
                ;;
        esac
    done
}

comfyui_addons(){
    CHOICES=$(whiptail --checklist "Addons:" 17 50 10 --cancel-button "Back" \
        1 "ComfyUI-Manager" ON \
        2 "ComfyUI-GGUF" ON \
        3 "ComfyUI-AuraSR" ON \
        4 "AuraFlow-v0.3" ON \
        8 "Qwen-Image GGUF" ON \
        9 "Qwen-Image-Edit GGUF" ON \
        10 "Qwen-Image-Edit-2509 GGUF" ON \
        11 "Wan2.2-TI2V-5B" ON 3>&1 1>&2 2>&3)

    status=$?


    if [ $status -ne 0 ]; then
        return 0
    fi

    install_comfyui $CHOICES
}

# Music generation
music_generation() {
    second=true
    while $second; do

        choice=$(whiptail --title "Music generation" --menu "Choose an option:" 15 100 1 --cancel-button "Back" \
            1 "Install ACE-Step" \
            2>&1 > /dev/tty)
        status=$?


        if [ $status -ne 0 ]; then
            return 0
        fi

        case "$choice" in
            "1")
                install_ace_step
                ;;
            "")
                echo "Previous menu..."
                second=false
                ;;
            *)
                echo "Invalid selection."
                second=false
                ;;
        esac
    done
}

# Voice generation
voice_generation() {
    second=true
    while $second; do

        choice=$(whiptail --title "Voice generation" --menu "Choose an option:" 15 100 6 --cancel-button "Back" \
            1 "Install WhisperSpeech web UI" \
            2 "Install F5-TTS" \
            3 "Install Matcha-TTS" \
            4 "Install Dia" \
            5 "Install Chatterbox Multilingual" \
            6 "Install KaniTTS" \
            2>&1 > /dev/tty)
        status=$?


        if [ $status -ne 0 ]; then
            return 0
        fi

        case "$choice" in
            "1")
                install_whisperspeech_web_ui
                ;;
            "2")
                install_f5_tts
                ;;
            "3")
                install_matcha_tts
                ;;
            "4")
                install_dia
                ;;
            "5")
                install_chatterbox_multilingual
                ;;
            "6")
                install_kanitts
                ;;
            "")
                echo "Previous menu..."
                second=false
                ;;
            *)
                echo "Invalid selection."
                second=false
                ;;
        esac
    done
}

# Function to display the main menu
show_menu() {
    choice=$(whiptail --title "ROCm-AI-Installer $VERSION" --menu "Choose an option:" 20 100 8 \
    1 "Variables" \
    2 "Create a container" \
    3 "Text generation" \
    4 "Image & video generation" \
    5 "Music generation" \
    6 "Voice generation" \
    7 "3D generation" \
    --cancel-button "Exit" \
    2>&1 > /dev/tty)

    case $choice in
        1)
            variables
            ;;
        2)
            create_container
            ;;
        3)
            text_generation
            ;;
        4)
            image_generation
            ;;
        5)
            music_generation
            ;;
        6)
            voice_generation
            ;;
        7)
            d3_generation
            ;;
        *)
            exit 0
            ;;
    esac
}

# 3D generation

d3_generation() {
    second=true
    while $second; do
        
        choice=$(whiptail --title "3D generation" --menu "Choose an option:" 15 100 1 --cancel-button "Back" \
            1 "Install PartCrafter" \
            2>&1 > /dev/tty)

        case "$choice" in
            "1")
                install_partcrafter
                ;;
            "")
                echo "Previous menu..."
                second=false
                ;;
            *)
                echo "Invalid selection."
                second=false
                ;;
        esac
        status=$?
        

        if [ $status -ne 0 ]; then
            return 0
        fi
    done
}

# Variables
variables() {
    second=true
    while $second; do

        choice=$(whiptail --title "Variables" --menu "Choose an option:" 15 100 4 --cancel-button "Back" \
            "1" "GFX" \
            "2" "HSA_OVERRIDE_GFX_VERSION" \
            "3" "PATH" \
            2>&1 > /dev/tty)
        status=$?

        if [ $status -ne 0 ]; then
            return 0
        fi

        case "$choice" in
            "1")
                configure_gfx
                ;;
            "2")
                configure_hsa
                ;;
            "3")
                configure_path
                ;;
            *)
                echo "Invalid selection."
                second=false
                ;;
        esac
    done
}

# Main execution
check_whiptail
load_config

# Main loop
while show_menu; do
    :
done