# ROCM-AI-Installer
# Copyright © 2023-2025 Mateusz Dera

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

version: '3.8'

services:
  rocm-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: rocm-ubuntu:7.1.1
    container_name: rocm
    hostname: rocm

    ports:
      - "5000:5000"
      - "5050:5050"
      - "7860:7860"
      - "7865:7865"
      - "8000:8000"
      - "8003:8003"
      - "8080:8080"
      - "8188:8188"

    # Pass through AMD GPU devices
    devices:
      - /dev/dri:/dev/dri              # Direct Rendering Infrastructure for GPU
      - /dev/kfd:/dev/kfd              # Kernel Fusion Driver for ROCm compute

    # Privileged mode for full GPU device access
    privileged: true

    # Security options for GPU access
    security_opt:
      - seccomp=unconfined
      - label=disable

    # Add capabilities for device access
    cap_add:
      - SYS_PTRACE

    # Keep host supplementary groups for proper device access
    # This ensures the container user inherits the host user's groups
    group_add:
      - keep-groups

    # Environment variables for ROCm
    environment:
      - ROCM_PATH=/opt/rocm
      - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-11.0.0}  # Configurable via setup.sh
      - TARGET_GFX=${TARGET_GFX:-gfx1100}  # Configurable via setup.sh
      - PYTORCH_ROCM_ARCH=${TARGET_GFX:-gfx1100}  # PyTorch ROCm architecture
      - GPU_DEVICE_ORDINAL=0
      - DISPLAY=${DISPLAY}  # X11 display for GUI applications

    # Keep container running
    stdin_open: true
    tty: true

    # Mount volumes for persistent data
    volumes:
      # Mount host directory to /AI in container
      # In rootless podman, root in container (UID 0) maps to host user
      - ${AI_HOST_DIR}:/AI
      - /etc/localtime:/etc/localtime:ro  # Inherit timezone from host
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 socket for GUI applications

    # Set working directory
    working_dir: /AI

    # Restart policy
    restart: unless-stopped
